apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-demo-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '.'
    targetRevision: HEAD
    path: argocd-apps/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 