apiVersion: v1
kind: Service
metadata:
  name: frontend-preview
  namespace: gitops-demo
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
    rollouts-pod-template-hash: canary
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30082 