apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '.'
    targetRevision: HEAD
    path: services/adservice
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 