apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shippingservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vellankikoti/argocd-microservices-demo.git'
    targetRevision: main
    path: services/shippingservice
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 